name: flutter_better_vlc_player
description: "A video player base VLC."
version: 1.2.0
homepage: https://github.com/SHINEPP/flutter_better_vlc_player
publish_to: "https://pub.dartlang.org"

environment:
  sdk: ^3.7.2
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2

  # keep screen on
  wakelock_plus: ^1.2.10

  # screen
  screen_brightness: ^2.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

  pigeon: ^25.3.1

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  # This section identifies this Flutter project as a plugin project.
  # The 'pluginClass' specifies the class (in Java, Kotlin, Swift, Objective-C, etc.)
  # which should be registered in the plugin registry. This is required for
  # using method channels.
  # The Android 'package' specifies package in which the registered class is.
  # This is required for using method channels on Android.
  # The 'ffiPlugin' specifies that native code should be built and bundled.
  # This is required for using `dart:ffi`.
  # All these are used by the tooling to maintain consistency when
  # adding or updating assets for this project.
  plugin:
    platforms:
      android:
        package: com.shinezzl.bettervlcplayer
        pluginClass: BetterVlcPlayerPlugin
      ios:
        pluginClass: BetterVlcPlayerPlugin
      macos:
        pluginClass: BetterVlcPlayerPlugin

