name: flutter_better_vlc_player
description: "A video player base VLC."
version: 1.2.1
homepage: https://github.com/SHINEPP/flutter_better_vlc_player

environment:
  sdk: ^3.7.2
  flutter: '>=3.3.0'

flutter:
  plugin:
    platforms:
      android:
        package: com.shinezzl.bettervlcplayer
        pluginClass: BetterVlcPlayerPlugin
      ios:
        pluginClass: BetterVlcPlayerPlugin
      macos:
        pluginClass: BetterVlcPlayerPlugin

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2

  # keep screen on
  wakelock_plus: ^1.2.10

  # screen
  screen_brightness: ^2.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

  pigeon: ^25.3.1

topics:
  - video-player
  - VLC
